// ecosystem.config.cjs — PM2 process manager configuration for Counsel Platform
// Usage: pm2 start ecosystem.config.cjs
//        pm2 status
//        pm2 logs
//        pm2 stop all
//        pm2 restart all

module.exports = {
  apps: [
    {
      name: 'counsel-api',
      cwd: './apps/api',
      script: 'node_modules/.bin/tsx',
      args: 'src/index.ts',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        CORS_ORIGIN: process.env.CORS_ORIGIN || 'https://app.counsel.ai',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      wait_ready: true,
      listen_timeout: 15000,
      kill_timeout: 10000,
    },
    {
      name: 'counsel-ai',
      cwd: './services/ai',
      script: 'python',
      args: '-m uvicorn src.main:app --host 127.0.0.1 --port 8000',
      interpreter: 'none', // PM2 should spawn python directly
      env: {
        PYTHONPATH: './services/ai',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '1G',
      error_file: './logs/ai-error.log',
      out_file: './logs/ai-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 30000,
    },
    {
      name: 'counsel-web',
      cwd: './apps/web',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      env: {
        NODE_ENV: 'production',
        NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || 'https://api.counsel.ai/api/v1',
      },
      instances: 1,
      autorestart: true,
      max_memory_restart: '512M',
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      kill_timeout: 10000,
    },
    // ── MCP Servers (17 total) ────────────────────────────────────────────
    {
      name: 'counsel-mcp-postgres',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.postgres_server',
      interpreter: 'none',
      env: { MCP_PORT: '3101', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-postgres-error.log', out_file: './logs/mcp-postgres-out.log',
    },
    {
      name: 'counsel-mcp-cloudflare',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.cloudflare_server',
      interpreter: 'none',
      env: { MCP_PORT: '3102', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-cloudflare-error.log', out_file: './logs/mcp-cloudflare-out.log',
    },
    {
      name: 'counsel-mcp-document',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.document_server',
      interpreter: 'none',
      env: { MCP_PORT: '3103', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-document-error.log', out_file: './logs/mcp-document-out.log',
    },
    {
      name: 'counsel-mcp-email',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.email_server',
      interpreter: 'none',
      env: { MCP_PORT: '3104', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-email-error.log', out_file: './logs/mcp-email-out.log',
    },
    {
      name: 'counsel-mcp-calendar',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.calendar_server',
      interpreter: 'none',
      env: { MCP_PORT: '3105', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-calendar-error.log', out_file: './logs/mcp-calendar-out.log',
    },
    {
      name: 'counsel-mcp-storage',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.storage_server',
      interpreter: 'none',
      env: { MCP_PORT: '3106', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-storage-error.log', out_file: './logs/mcp-storage-out.log',
    },
    {
      name: 'counsel-mcp-esign',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.esign_server',
      interpreter: 'none',
      env: { MCP_PORT: '3107', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-esign-error.log', out_file: './logs/mcp-esign-out.log',
    },
    {
      name: 'counsel-mcp-billing',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.billing_server',
      interpreter: 'none',
      env: { MCP_PORT: '3108', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-billing-error.log', out_file: './logs/mcp-billing-out.log',
    },
    {
      name: 'counsel-mcp-court',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.court_server',
      interpreter: 'none',
      env: { MCP_PORT: '3109', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-court-error.log', out_file: './logs/mcp-court-out.log',
    },
    {
      name: 'counsel-mcp-communication',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.communication_server',
      interpreter: 'none',
      env: { MCP_PORT: '3110', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-communication-error.log', out_file: './logs/mcp-communication-out.log',
    },
    {
      name: 'counsel-mcp-crm',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.crm_server',
      interpreter: 'none',
      env: { MCP_PORT: '3111', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-crm-error.log', out_file: './logs/mcp-crm-out.log',
    },
    {
      name: 'counsel-mcp-workflow',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.workflow_server',
      interpreter: 'none',
      env: { MCP_PORT: '3112', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-workflow-error.log', out_file: './logs/mcp-workflow-out.log',
    },
    {
      name: 'counsel-mcp-ocr',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.ocr_server',
      interpreter: 'none',
      env: { MCP_PORT: '3113', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-ocr-error.log', out_file: './logs/mcp-ocr-out.log',
    },
    {
      name: 'counsel-mcp-translation',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.translation_server',
      interpreter: 'none',
      env: { MCP_PORT: '3114', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-translation-error.log', out_file: './logs/mcp-translation-out.log',
    },
    {
      name: 'counsel-mcp-video',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.video_server',
      interpreter: 'none',
      env: { MCP_PORT: '3115', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-video-error.log', out_file: './logs/mcp-video-out.log',
    },
    {
      name: 'counsel-mcp-time',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.time_server',
      interpreter: 'none',
      env: { MCP_PORT: '3116', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-time-error.log', out_file: './logs/mcp-time-out.log',
    },
    {
      name: 'counsel-mcp-conflict',
      cwd: './services/ai',
      script: 'python',
      args: '-m src.mcp.conflict_server',
      interpreter: 'none',
      env: { MCP_PORT: '3117', PYTHONPATH: './services/ai' },
      instances: 1, autorestart: true, max_memory_restart: '256M',
      error_file: './logs/mcp-conflict-error.log', out_file: './logs/mcp-conflict-out.log',
    },
  ],
};
